### ISSUE TITLE
API - line feed characters in input causes an error

### ISSUE THREAD

**Issue by CrazyTim** [sqlparser/sql-pretty-printer#2]
Including 1 or more line feed characters (url encoded = %0a) in SQL causes the error:

"rspn_formatted_sql" : "Input SQL is empty!"

**Comment by nlargebiz** [comment]
Hi.

If I post the formatter configuration file fo.json to the intended directory Notepad++\Plugins\Config\sqlformat and then try to format the following text I get the same issue as the user in this post - "Input SQL is empty!".  If I remove the fo.json file and related config structure (essentially undoing the addition of the config file) It works, but of course I cannot configure the plugin without it.  The following SQL is what I am trying to format ...

select * from table1

Using: Windows 10 Pro V.1511 OS Build 10586.873
           Notepad++ v7.3.3

I have tried putting the following in the contextMenu.xml file but it does not have any effect on the outcome.

<Item FolderName="Plugin commands" PluginEntryName="SQL Format" PluginCommandItemName="Format" ItemNameAs="Format SQL"/>
           
Please advise.

Sincerely, Nick.
